apiVersion: v1
kind: Service
metadata:
  name: homelab-api
  namespace: homelab
spec:
  # Route traffic to pods created by the homelab-api Deployment.
  selector:
    app: homelab-api
  # ClusterIP is the default and simplest way to expose traffic within the cluster.
  type: ClusterIP
  ports:
  # Expose service port 80 and forward to container port 8080.
  - port: 80
    targetPort: 8080
    # Must match kind extraPortMappings containerPort in kind/cluster.yml.
    protocol: TCP

